# AIRPORT CODE COLUMN LABELS
AIRPORT_NUM = "Num"
AIRPORT_CODE = "AirportCode"
AIRPORT_COUNTRY = "Country"
AIRPORT_COUNTRY_CODE = "CountryCode"
AIRPORT_REGION = "Region"
COUNTRY = "Country"

# HOTEL OCCUPANCY COLUMN LABELS
HOTEL_OCCUPANCY_DATE = "Date"
ASIA_PACIFIC = "AsiaPacific"
AMERICAS = "Americas"
EUROPE = "Europe"
ME_AFRICA = "MiddleEastAfrica"

# OUTPUT FIELD COLUMN LABELS
FARE_ID = "FAREID"
DEPARTURE_DATE = "DEPARTURE_DATE"
MARKET_SHARE = "MS_PERC"
ORIGIN = "ORIG"
DESTINATION = "DEST"
FARE_FUEL_INSURANCE = "YQ_YR_AMT_BC"
FARE_FUEL_SURCHARGE = "Q_FUEL_AMT_BC"
FARE_BASE = "FAREAMT_BC"
FARE_TAX = "TAX_AMT_BC"
FARE_MISC = "Q_OTHERS_AMT_BC"
FARE_TOTAL = "TOTAL_AMT_BC"


def isBlank(string):
    s = str(string)
    return not bool(s and s.strip())